### ISSUE TITLE
Video location for collection

### ISSUE THREAD

**Issue by pingSubhajit** [pingArnab/HERA#1]
The API Call for `http://127.0.0.1:8000/api/v1/movie-collection/collectionID` returns the parts of that particular collection but does not return the location of the movies in the collection. The location is necessary to play the videos directly from the collection page.

Also, it is required to sort the videos in the part of a collection by their release data so that they can be displayed in order.

**Comment by pingArnab** [comment]
fix provided 
commit-msg: Issue-1. Video location for collection #1 - fix

**Comment by pingSubhajit** [comment]
`ImproperlyConfigured at /api/v1/random-collection/
Field name `location` is not valid for model `Media`.`

**Comment by pingArnab** [comment]
fix provided
commit-msg: **Issue-1. Video location for collection #1 - fix v2**
