### ISSUE TITLE
Adding a TV show to wishlist returns an error

### ISSUE THREAD

**Issue by pingSubhajit** [pingArnab/HERA#4]
**Description**

If a TV show is added to a user's wishlist using the API, the backend crashes returning the below mentioned error. But adding movie to the wishlist works perfectly.

**API in question**

POST: http://127.0.0.1:8000/api/v1/user/wishlist/

**Returned Error**

'Video' instance expected, got <TVShow: Lucifer [63174]>

@pingArnab

**Comment by pingArnab** [comment]
FIX Provided

**Comment by pingSubhajit** [comment]
Adding a TV show to wishlish works now but it returns an error when deleting the TV show from wishlist.

**Comment by pingArnab** [comment]
FIX Provided
